---
abstract: 'clean up text to use as URL fragment or filename'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Carp: '0'
  Data::Dumper: '0'
  Exporter: '5'
  Test::More: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-CleanFragment
no_index:
  directory:
    - t
    - inc
requires:
  Text::Unidecode: '0'
  perl: '5.008'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/text-cleanfragment.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
