---
abstract: 'clean up text to use as URL fragment or filename'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Carp: '0'
  Exporter: '5'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-CleanFragment
no_index:
  directory:
    - t
    - inc
requires:
  Text::Unidecode: '0'
  perl: '5.006'
version: '0.03'
x_bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-CleanFragment
x_repository:
  type: git
  url: git://github.com/Corion/text-cleanfragment.git
  web: https://github.com/Corion/text-cleanfragment
x_static_install: 1
